jobs:
  build_and_deploy:
    docker:
      - image: 'google/cloud-sdk:alpine'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_SHA1}'
      - cloudrun/deploy:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_SHA1}'
          platform: managed
          region: ${GOOGLE_COMPUTE_ZONE}
          service-name: website
          unauthenticated: true
      - run:
          name: Cleanup Container Registry
          command: gcloud container images delete gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_SHA1}:latest
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - deploy_hold:
          type: approval
          filters:
            branches: 
              only: master
      - build_and_deploy:
          requires:
            - deploy_hold